# Generated by Django 5.0.7 on 2025-08-01 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('c_bussniess_type', models.CharField(max_length=50)),
                ('c_industry_type', models.CharField(max_length=50)),
                ('c_gst_number', models.CharField(default=None, max_length=24, unique=True)),
                ('c_pan_number', models.CharField(max_length=10, unique=True)),
                ('c_tan_number', models.CharField(max_length=10, unique=True)),
                ('c_cin_number', models.CharField(max_length=21, unique=True)),
                ('c_contact_person', models.CharField(blank=True, max_length=100, null=True)),
                ('c_contact_designation', models.CharField(blank=True, max_length=100, null=True)),
                ('c_contact_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('c_contact_mobile', models.CharField(blank=True, max_length=12, null=True)),
                ('c_office_address', models.CharField(blank=True, max_length=100, null=True)),
                ('c_office_state', models.CharField(blank=True, max_length=20, null=True)),
                ('c_office_city', models.CharField(blank=True, max_length=50, null=True)),
                ('c_office_pincode', models.CharField(blank=True, max_length=6, null=True)),
                ('c_billing_address', models.CharField(blank=True, max_length=100, null=True)),
                ('c_billing_state', models.CharField(blank=True, max_length=20, null=True)),
                ('c_billing_city', models.CharField(blank=True, max_length=50, null=True)),
                ('c_billing_pincode', models.CharField(blank=True, max_length=6, null=True)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company_user')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tender_id', models.BigIntegerField(unique=True)),
                ('tender_title', models.CharField(max_length=200)),
                ('contarct_number', models.CharField(max_length=50, unique=True)),
                ('tender_value', models.BigIntegerField()),
                ('payment_terms', models.CharField(default=None, max_length=2000)),
                ('scope_of_work', models.CharField(max_length=2000)),
                ('project_type', models.CharField(max_length=500)),
                ('dilivery_location', models.CharField(max_length=700)),
                ('contract_start_date', models.DateField(default=None)),
                ('contract_end_date', models.DateField(default=None)),
                ('contract_status', models.CharField(default='Pending', max_length=100)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client_profile')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company_user')),
            ],
        ),
    ]
