# Generated by Django 5.0.7 on 2025-08-01 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=20)),
                ('gst_number', models.CharField(max_length=24, unique=True)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('mobile', models.BigIntegerField(unique=True)),
                ('password', models.CharField(max_length=3128)),
                ('company_profile_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Company_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bussniess_type', models.CharField(max_length=50)),
                ('industry_type', models.CharField(max_length=50)),
                ('pan_number', models.CharField(max_length=10, unique=True)),
                ('tan_number', models.CharField(max_length=10, unique=True)),
                ('cin_number', models.CharField(max_length=21, unique=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=20, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('pincode', models.CharField(blank=True, max_length=6, null=True)),
                ('website', models.CharField(blank=True, max_length=200, null=True)),
                ('logo', models.FileField(blank=True, null=True, upload_to='company_logos/')),
                ('tagline', models.CharField(blank=True, max_length=100, null=True)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company_user')),
            ],
        ),
    ]
