# Generated by Django 5.2.5 on 2025-10-15 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company_profile',
            name='bussniess_type',
        ),
        migrations.RemoveField(
            model_name='company_profile',
            name='cin_number',
        ),
        migrations.RemoveField(
            model_name='company_profile',
            name='industry_type',
        ),
        migrations.RemoveField(
            model_name='company_profile',
            name='tagline',
        ),
        migrations.RemoveField(
            model_name='company_profile',
            name='tan_number',
        ),
        migrations.RemoveField(
            model_name='company_profile',
            name='website',
        ),
    ]
