# Generated by Django 5.2.5 on 2026-03-17 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_remove_company_profile_bussniess_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_user',
            name='company_name',
            field=models.CharField(max_length=100),
        ),
    ]
