# Generated by Django 5.2.5 on 2026-03-17 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_company_user_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_user',
            name='mobile',
            field=models.BigIntegerField(),
        ),
    ]
