# Generated by Django 5.0.7 on 2025-08-01 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=500)),
                ('destination', models.CharField(max_length=500)),
                ('km', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
