# Generated by Django 5.0.7 on 2025-08-04 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='distric',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='route',
            name='taluka',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
