# Generated by Django 5.0.7 on 2025-08-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_route_distric_route_taluka'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rent_slip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depature_date', models.DateField()),
                ('center', models.CharField(max_length=500)),
                ('truck_no', models.CharField(max_length=500)),
                ('truck_onwer_name', models.CharField(max_length=500)),
                ('driver_name', models.CharField(max_length=500)),
                ('mobile_no', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=500)),
                ('license_no', models.CharField(max_length=500)),
                ('rto', models.CharField(max_length=500)),
                ('declaration', models.CharField(max_length=500)),
                ('pancard_no', models.CharField(max_length=500)),
                ('pancard_holder_name', models.CharField(max_length=500)),
                ('memo_number', models.CharField(max_length=500)),
                ('type_of_goods', models.CharField(max_length=500)),
                ('consignor_name', models.CharField(max_length=500)),
                ('consignee_name', models.CharField(max_length=500)),
                ('village', models.CharField(max_length=500)),
                ('taluka', models.CharField(max_length=500)),
                ('district', models.CharField(max_length=500)),
                ('number_of_bags', models.IntegerField()),
                ('total_freight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('freight_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rupees_per_ton', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('laboring', models.DecimalField(decimal_places=2, max_digits=10)),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('advance_payment', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
