# Generated by Django 5.0.7 on 2025-08-04 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0003_rent_slip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent_slip',
            name='advance_payment',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='rent_slip',
            name='freight_rate',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='rent_slip',
            name='grand_total',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='rent_slip',
            name='laboring',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='rent_slip',
            name='rupees_per_ton',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='rent_slip',
            name='total_freight',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='rent_slip',
            name='total_weight',
            field=models.BigIntegerField(),
        ),
    ]
