# Generated by Django 5.0.7 on 2025-08-06 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0004_alter_rent_slip_advance_payment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LR_slip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lr_no', models.CharField(max_length=20)),
                ('depature_date', models.DateField()),
                ('expeted_delivery_date', models.DateField()),
                ('truck_no', models.CharField(max_length=500)),
                ('driver_name', models.CharField(max_length=500)),
                ('mobile_no', models.CharField(max_length=500)),
                ('type_of_goods', models.CharField(max_length=500)),
                ('consignor_name', models.CharField(max_length=500)),
                ('consignee_name', models.CharField(max_length=500)),
                ('dilivery_location', models.CharField(max_length=500)),
                ('total_freight', models.BigIntegerField()),
                ('freight_rate', models.BigIntegerField()),
                ('rupees_per_ton', models.BigIntegerField()),
                ('total_weight', models.BigIntegerField()),
                ('laboring', models.BigIntegerField()),
                ('grand_total', models.BigIntegerField()),
                ('advance_payment', models.BigIntegerField()),
            ],
        ),
    ]
