# Generated by Django 5.0.7 on 2025-08-06 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0005_lr_slip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lr_slip',
            name='freight_rate',
        ),
        migrations.AddField(
            model_name='lr_slip',
            name='rent_slip_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='transport.rent_slip'),
        ),
    ]
