# Generated by Django 5.0.7 on 2025-08-06 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0006_remove_lr_slip_freight_rate_lr_slip_rent_slip_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lr_slip',
            name='rent_slip_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.rent_slip'),
        ),
    ]
