# Generated by Django 5.0.7 on 2025-08-07 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('transport', '0007_alter_lr_slip_rent_slip_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_no', models.CharField(max_length=20)),
                ('inv_date', models.DateField()),
                ('gst', models.CharField(max_length=20)),
                ('total_freight', models.BigIntegerField()),
                ('advance_payment', models.BigIntegerField()),
                ('taxable_amount', models.BigIntegerField()),
                ('gst_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('gst_amount', models.BigIntegerField(default=0)),
                ('laboring', models.BigIntegerField(default=0)),
                ('grand_total', models.BigIntegerField()),
                ('payment_status', models.CharField(max_length=10)),
                ('due_date', models.DateField()),
                ('client_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client_profile')),
                ('lr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.lr_slip')),
            ],
        ),
    ]
