# Generated by Django 5.0.7 on 2025-08-07 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0008_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Truck_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_no', models.CharField(max_length=12, unique=True)),
                ('vehicle_type', models.CharField(max_length=200)),
                ('onwer_name', models.CharField(max_length=200)),
                ('rc_no', models.CharField(max_length=200)),
                ('inss_no', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
