# Generated by Django 5.0.7 on 2025-08-07 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0009_truck_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck_details',
            name='onwer_mobile',
            field=models.BigIntegerField(default=None),
        ),
    ]
