# Generated by Django 5.0.7 on 2025-08-07 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0010_truck_details_onwer_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck_details',
            name='truck_no',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
