# Generated by Django 5.0.7 on 2025-08-08 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0011_alter_truck_details_truck_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='total_weight',
            field=models.BigIntegerField(default=0),
        ),
    ]
