# Generated by Django 5.0.7 on 2025-08-08 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0012_invoice_total_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='rate_per_ton',
            field=models.BigIntegerField(default=0),
        ),
    ]
