# Generated by Django 5.2.5 on 2025-08-20 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0013_invoice_rate_per_ton'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True)),
                ('mobile', models.CharField(max_length=200)),
                ('license_number', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
