# Generated by Django 5.2.5 on 2025-08-20 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0015_alter_driver_details_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver_details',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
