# Generated by Django 5.2.5 on 2025-08-21 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0016_alter_driver_details_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='gst_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
