# Generated by Django 5.2.5 on 2025-08-26 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0017_alter_invoice_grand_total_alter_invoice_gst_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent_slip',
            name='from_location',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
