# Generated by Django 5.2.5 on 2025-08-26 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0018_rent_slip_from_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent_slip',
            name='km',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
