# Generated by Django 5.2.5 on 2025-08-26 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('transport', '0019_rent_slip_km'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver_details',
            name='company_user_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='company.company_user'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='company_user_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='company.company_user'),
        ),
        migrations.AddField(
            model_name='lr_slip',
            name='company_user_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='company.company_user'),
        ),
        migrations.AddField(
            model_name='rent_slip',
            name='company_user_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='company.company_user'),
        ),
        migrations.AddField(
            model_name='route',
            name='company_user_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='company.company_user'),
        ),
        migrations.AddField(
            model_name='truck_details',
            name='company_user_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='company.company_user'),
        ),
    ]
