# Generated by Django 5.2.5 on 2025-08-27 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0020_driver_details_company_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent_slip',
            name='km',
            field=models.CharField(max_length=500),
        ),
    ]
