# Generated by Django 5.2.5 on 2025-08-28 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('company', '0001_initial'),
        ('transport', '0021_alter_rent_slip_km'),
    ]

    operations = [
        migrations.CreateModel(
            name='New_contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_no', models.CharField(max_length=120)),
                ('bill_date', models.DateField()),
                ('c_address', models.CharField(max_length=300)),
                ('c_gst', models.CharField(max_length=300)),
                ('product', models.CharField(max_length=300)),
                ('chalan_no', models.CharField(max_length=100)),
                ('loading_date', models.DateField()),
                ('truck_no', models.CharField(max_length=100)),
                ('party_name', models.CharField(max_length=200)),
                ('hsn_code', models.CharField(max_length=100)),
                ('rack_name', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate', models.BigIntegerField()),
                ('qty', models.BigIntegerField()),
                ('tra_amount', models.BigIntegerField()),
                ('unload_amount', models.BigIntegerField()),
                ('loading_amount', models.BigIntegerField(default=0)),
                ('de_unloading_amount', models.BigIntegerField(default=0)),
                ('grand_total', models.BigIntegerField()),
                ('payment_status', models.CharField(max_length=50)),
                ('due_date', models.DateField()),
                ('client_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client_profile')),
                ('company_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='company.company_user')),
            ],
        ),
    ]
