# Generated by Django 5.2.5 on 2025-08-28 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0022_new_contract'),
    ]

    operations = [
        migrations.RenameField(
            model_name='truck_details',
            old_name='company_user_id',
            new_name='company_id',
        ),
    ]
