# Generated by Django 5.2.5 on 2025-08-28 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('company', '0001_initial'),
        ('transport', '0023_rename_company_user_id_truck_details_company_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_type', models.CharField(max_length=100)),
                ('from_km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('to_km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mt_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mtkm_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('client_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client_profile')),
                ('company_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='company.company_user')),
            ],
        ),
    ]
