# Generated by Django 5.2.5 on 2025-09-03 04:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0024_rate_master'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='T_Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('gst_number', models.CharField(blank=True, max_length=50, null=True)),
                ('pan_number', models.CharField(blank=True, max_length=20, null=True)),
                ('tan_number', models.CharField(blank=True, max_length=20, null=True)),
                ('cin_number', models.CharField(blank=True, max_length=50, null=True)),
                ('from_center', models.CharField(blank=True, max_length=100, null=True)),
                ('contract_no', models.CharField(max_length=50, unique=True)),
                ('bill_series_from', models.CharField(blank=True, max_length=20, null=True)),
                ('bill_series_to', models.CharField(blank=True, max_length=20, null=True)),
                ('c_start_date', models.DateField(blank=True, null=True)),
                ('c_end_date', models.DateField(blank=True, null=True)),
                ('cp_name', models.CharField(blank=True, max_length=100, null=True)),
                ('c_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('c_designation', models.CharField(blank=True, max_length=100, null=True)),
                ('c_number', models.CharField(blank=True, max_length=15, null=True)),
                ('office_address', models.TextField(blank=True, null=True)),
                ('office_state', models.CharField(blank=True, max_length=50, null=True)),
                ('office_city', models.CharField(blank=True, max_length=50, null=True)),
                ('office_pin', models.CharField(blank=True, max_length=10, null=True)),
                ('billing_address', models.TextField(blank=True, null=True)),
                ('billing_state', models.CharField(blank=True, max_length=50, null=True)),
                ('billing_city', models.CharField(blank=True, max_length=50, null=True)),
                ('billing_pin', models.CharField(blank=True, max_length=10, null=True)),
                ('unloading_rate', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=5)),
                ('unloading_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('invoice_fields', models.JSONField(blank=True, default=list, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_type', models.CharField(blank=True, choices=[('Kilometer-Wise', 'Kilometer-Wise'), ('Taluka-Wise', 'Taluka-Wise'), ('Slab-Wise', 'Slab-Wise'), ('Distric-Wise', 'Distric-Wise')], max_length=50, null=True)),
                ('from_km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('to_km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mt_per_km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='transport.t_contract')),
            ],
        ),
    ]
