# Generated by Django 5.2.5 on 2025-09-03 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('transport', '0025_t_contract_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_contract',
            name='user',
        ),
        migrations.AddField(
            model_name='t_contract',
            name='company_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='company.company_user'),
        ),
    ]
