# Generated by Django 5.2.5 on 2025-09-03 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('transport', '0026_remove_t_contract_user_t_contract_company_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='company_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='company.company_user'),
        ),
    ]
