# Generated by Django 5.2.5 on 2025-09-03 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('transport', '0027_rate_company_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_center', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('taluka', models.CharField(max_length=255)),
                ('km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('company_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='company.company_user')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.t_contract')),
            ],
        ),
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_date', models.DateField(blank=True, null=True)),
                ('challan_no', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('truck_no', models.CharField(max_length=50)),
                ('product_name', models.CharField(max_length=150)),
                ('party_name', models.CharField(max_length=200)),
                ('from_center', models.CharField(max_length=200)),
                ('destination', models.CharField(blank=True, max_length=200, null=True)),
                ('taluka', models.CharField(blank=True, max_length=200, null=True)),
                ('district', models.CharField(blank=True, max_length=200, null=True)),
                ('km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('totalfreight', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unloading_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('advance_payment', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='company.company_user')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatches', to='transport.t_contract')),
            ],
        ),
    ]
