# Generated by Django 5.2.5 on 2025-09-03 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0028_destination_dispatch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dispatch',
            old_name='advance_payment',
            new_name='advance_paid',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='dispatch',
            name='contract',
        ),
        migrations.AddField(
            model_name='destination',
            name='contract_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='transport.t_contract'),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='contract_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='transport.t_contract'),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='net_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='panding_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='total_paid_truck_onwer',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='truck_booking_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='destination',
            name='destination',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='destination',
            name='district',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='destination',
            name='from_center',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='destination',
            name='taluka',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='destination',
            field=models.CharField(default=0, max_length=150),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='district',
            field=models.CharField(default=0, max_length=150),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='from_center',
            field=models.CharField(default=0, max_length=150),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='km',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='party_name',
            field=models.CharField(default=0, max_length=150),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='taluka',
            field=models.CharField(default=0, max_length=150),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='unloading_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
