# Generated by Django 5.2.5 on 2025-09-18 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0029_rename_advance_payment_dispatch_advance_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='taluka_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
