# Generated by Django 5.2.5 on 2025-09-18 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0030_rate_taluka_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='taluka_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
