# Generated by Django 5.2.5 on 2025-09-18 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0031_rate_taluka_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_contract',
            name='rate_type',
            field=models.CharField(blank=True, choices=[('Kilometer-Wise', 'Kilometer-Wise'), ('Taluka-Wise', 'Taluka-Wise'), ('Slab-Wise', 'Slab-Wise'), ('Distric-Wise', 'Distric-Wise')], max_length=50, null=True),
        ),
    ]
