# Generated by Django 5.2.5 on 2025-09-19 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('transport', '0032_t_contract_rate_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='taluka_name',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='taluka_rate',
        ),
        migrations.AlterField(
            model_name='rate',
            name='rate_type',
            field=models.CharField(blank=True, choices=[('Kilometer-Wise', 'Kilometer-Wise')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Rate_taluka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_type', models.CharField(blank=True, choices=[('Taluka-Wise', 'Taluka-Wise')], max_length=50, null=True)),
                ('distric_name', models.CharField(max_length=50)),
                ('taluka_name', models.CharField(max_length=50)),
                ('mt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('company_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='company.company_user')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Taluka_rates', to='transport.t_contract')),
            ],
        ),
    ]
