# Generated by Django 5.2.5 on 2025-09-26 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0033_remove_rate_taluka_name_remove_rate_taluka_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_contract',
            name='dc_field',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
