# Generated by Django 5.2.5 on 2025-09-26 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('transport', '0034_t_contract_dc_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate_District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_type', models.CharField(blank=True, choices=[('Distric-Wise', 'Distric-Wise')], max_length=50, null=True)),
                ('distric_name', models.CharField(max_length=50)),
                ('mt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mt_per_km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('company_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='company.company_user')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='District_rates', to='transport.t_contract')),
            ],
        ),
    ]
