# Generated by Django 5.2.5 on 2025-09-29 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0035_rate_district'),
    ]

    operations = [
        migrations.DeleteModel(
            name='New_contract',
        ),
    ]
