# Generated by Django 5.2.5 on 2025-09-29 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0036_delete_new_contract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='client_name',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='company_user_id',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='lr_id',
        ),
        migrations.RemoveField(
            model_name='lr_slip',
            name='company_user_id',
        ),
        migrations.RemoveField(
            model_name='lr_slip',
            name='rent_slip_id',
        ),
        migrations.RemoveField(
            model_name='rate_master',
            name='client_name',
        ),
        migrations.RemoveField(
            model_name='rate_master',
            name='company_id',
        ),
        migrations.RemoveField(
            model_name='rent_slip',
            name='company_user_id',
        ),
        migrations.RemoveField(
            model_name='route',
            name='company_user_id',
        ),
        migrations.RemoveField(
            model_name='truck_details',
            name='company_id',
        ),
        migrations.DeleteModel(
            name='Driver_details',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='LR_slip',
        ),
        migrations.DeleteModel(
            name='Rate_master',
        ),
        migrations.DeleteModel(
            name='Rent_slip',
        ),
        migrations.DeleteModel(
            name='Route',
        ),
        migrations.DeleteModel(
            name='Truck_details',
        ),
    ]
