# Generated by Django 5.2.5 on 2025-10-03 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('transport', '0037_remove_invoice_client_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate_IncomeTax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_type', models.CharField(blank=True, choices=[('Kilometer-Wise', 'Kilometer-Wise')], max_length=50, null=True)),
                ('from_km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('to_km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mt_per_km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('company_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='company.company_user')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='IncomeTax_rates', to='transport.t_contract')),
            ],
        ),
    ]
