# Generated by Django 5.2.5 on 2025-10-08 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0039_rate_cumulative'),
    ]

    operations = [
        migrations.RenameField(
            model_name='t_contract',
            old_name='unloading_charge',
            new_name='unloading_charge_1',
        ),
        migrations.RemoveField(
            model_name='t_contract',
            name='unloading_rate',
        ),
        migrations.AddField(
            model_name='t_contract',
            name='loading_charge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='t_contract',
            name='unloading_charge_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
