# Generated by Django 5.2.5 on 2025-10-08 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0040_rename_unloading_charge_t_contract_unloading_charge_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dispatch',
            old_name='unloading_charge',
            new_name='unloading_charge_1',
        ),
        migrations.AddField(
            model_name='dispatch',
            name='loading_charge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='unloading_charge_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
