# Generated by Django 5.2.5 on 2025-10-08 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('transport', '0041_rename_unloading_charge_dispatch_unloading_charge_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatch',
            name='inv_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Generated', 'Generated')], default='Pending', max_length=50),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bill_no', models.CharField(max_length=50, unique=True)),
                ('Bill_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='company.company_user')),
                ('contract_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='transport.t_contract')),
                ('dispatch_list', models.ManyToManyField(related_name='invoices', to='transport.dispatch')),
            ],
        ),
    ]
