# Generated by Django 5.2.5 on 2025-10-08 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0042_dispatch_inv_status_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatch',
            name='inv_status',
            field=models.BooleanField(default=False, max_length=50),
        ),
    ]
