# Generated by Django 5.2.5 on 2025-10-09 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('transport', '0043_alter_dispatch_inv_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='GC_Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gc_no', models.CharField(max_length=50, unique=True)),
                ('gc_date', models.DateField(blank=True, null=True)),
                ('consignor', models.CharField(max_length=255)),
                ('consignee', models.CharField(max_length=255)),
                ('dispatch_from', models.CharField(max_length=255)),
                ('dc_field', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('product_name', models.CharField(max_length=255)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('truck_no', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=100)),
                ('bill_no', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='company.company_user')),
                ('contract_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='transport.t_contract')),
                ('dispatch_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='transport.dispatch')),
            ],
        ),
        migrations.AddField(
            model_name='dispatch',
            name='gc_note_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport.gc_note'),
        ),
    ]
