# Generated by Django 5.2.5 on 2025-10-09 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0044_gc_note_dispatch_gc_note_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatch',
            name='gc_note_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
