# Generated by Django 5.2.5 on 2025-10-09 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0045_alter_dispatch_gc_note_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dispatch',
            old_name='gc_note_id',
            new_name='gc_note_no',
        ),
    ]
