# Generated by Django 5.2.5 on 2025-10-09 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0046_rename_gc_note_id_dispatch_gc_note_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='gc_note',
            name='bill_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='transport.invoice'),
        ),
    ]
