# Generated by Django 5.2.5 on 2025-10-10 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0047_gc_note_bill_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='Bill_no',
            field=models.CharField(max_length=50),
        ),
    ]
