# Generated by Django 5.2.5 on 2025-10-15 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0048_alter_invoice_bill_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_contract',
            name='office_address',
        ),
        migrations.RemoveField(
            model_name='t_contract',
            name='office_city',
        ),
        migrations.RemoveField(
            model_name='t_contract',
            name='office_pin',
        ),
        migrations.RemoveField(
            model_name='t_contract',
            name='office_state',
        ),
    ]
