# Generated by Django 5.2.5 on 2025-11-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0050_alter_destination_km_alter_dispatch_advance_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='km',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='rate',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='totalfreight',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='rate',
            name='from_km',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='rate',
            name='to_km',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='rate_cumulative',
            name='from_km',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='rate_cumulative',
            name='to_km',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='rate_incometax',
            name='from_km',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='rate_incometax',
            name='to_km',
            field=models.BigIntegerField(),
        ),
    ]
