# Generated by Django 5.2.5 on 2025-11-03 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0051_alter_destination_km_alter_dispatch_grand_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatch',
            name='km',
            field=models.BigIntegerField(),
        ),
    ]
