# Generated by Django 5.2.5 on 2025-11-07 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0052_alter_dispatch_km'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispatch',
            name='date',
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='dep_date',
            field=models.DateField(default=None),
        ),
    ]
