# Generated by Django 5.2.5 on 2025-11-07 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0053_remove_dispatch_date_alter_dispatch_dep_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='taluka',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
    ]
