# Generated by Django 5.2.5 on 2025-11-07 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0054_alter_destination_taluka'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_contract',
            name='gc_note_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='t_contract',
            name='gc_series_from',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='t_contract',
            name='gc_series_to',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
