# Generated by Django 5.2.5 on 2025-11-07 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0055_t_contract_gc_note_required_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_contract',
            name='gc_series_to',
        ),
    ]
