# Generated by Django 5.2.5 on 2025-11-07 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0056_remove_t_contract_gc_series_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gc_note',
            name='gc_no',
            field=models.BigIntegerField(max_length=50, unique=True),
        ),
    ]
