# Generated by Django 5.2.5 on 2025-11-07 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0057_alter_gc_note_gc_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gc_note',
            name='gc_no',
            field=models.BigIntegerField(max_length=50),
        ),
    ]
