# Generated by Django 5.2.5 on 2026-01-19 07:41

import transport.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0059_alter_gc_note_gc_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='rr_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='dep_date',
            field=models.DateField(default=transport.models.get_today),
        ),
    ]
