# Generated by Django 5.2.5 on 2026-01-30 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0061_t_contract_vendor_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatch',
            name='main_party',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='sub_party',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
