# Generated by Django 5.2.5 on 2026-03-13 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0062_dispatch_main_party_dispatch_sub_party'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_contract',
            name='footer_company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='t_contract',
            name='show_recommended_by',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='t_contract',
            name='show_verified_by',
            field=models.BooleanField(default=False),
        ),
    ]

