# Generated by Django 5.2.5 on 2026-03-13 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0063_t_contract_invoice_footer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatch',
            name='totalfreight',
            field=models.DecimalField(decimal_places=6, max_digits=12),
        ),
    ]
