# Generated by Django 5.2.5 on 2026-06-01 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0068_rateslabrevision'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='rateslabrevision',
            new_name='transport_r_contrac_eb85a3_idx',
            old_name='transport_r_contrac_8a1f2d_idx',
        ),
        migrations.RenameIndex(
            model_name='rateslabrevision',
            new_name='transport_r_contrac_124f22_idx',
            old_name='transport_r_contrac_9b3e4f_idx',
        ),
    ]
